meta_product_name: "Busy Bear"
meta_title: "BusyBear - The app for the busy business person and the idle studen"
meta_description: " Students, Gigs, Jobs, cheap, local, errands, sitting, pets, babysitting "
meta_image: "og_image.jpg"
